version: '2.1'
services:
  web: 
    image: "web-server"
    volumes:
      - ./bin/:/binaries
      - ${GOPATH}/src/:/go/src
      - ./:/chirp-viewer
    ports:
      - "8000:8000" 
  generator:
    image: "data-generator"
  oauth2-proxy:
    image: "wingedkiwi/oauth2-proxy"
    ports:
     - "4180:4180"
    entrypoint:
    - oauth2_proxy
    - --cookie-secret=l46rx5eRy+AZUsMUs8aGVBOPcjXfETOpn1Ityb76MU=
    - --cookie-secure=false
    - --upstream=http://web:8000
    - --client-id=595670537468-62ghhlk39it20bt19io0aro4ftba78tu.apps.googleusercontent.com
    - --client-secret=cBUW8IsIQl8G47Dq1qieDzkA
    - --http-address=http://0.0.0.0:4180
    - --email-domain=*
  influx:
    image: "influxdb:alpine"
    ports:
      - "8086:8086"
