version: '2.1'
services:
  web: 
    image: "uforic/web-server-prod"
  generator:
    image: "uforic/data-generator"
  oauth2-proxy:
    image: "wingedkiwi/oauth2-proxy"
    ports:
     - "4180:4180"
    entrypoint:
    - oauth2_proxy
    - --cookie-secret=${COOKIE_SECRET}
    - --cookie-secure=false
    - --upstream=http://web:8000
    - --client-id=${CLIENT_ID}
    - --client-secret=${CLIENT_SECRET}
    - --http-address=http://0.0.0.0:4180
    - --email-domain=*
  influx:
    image: "influxdb:alpine"
    ports:
      - "8086:8086"
