FROM golang:latest
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install nodejs
RUN echo "alias node='nodejs'" >> ~/.bashrc
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install \
    yarn
WORKDIR /chirp-viewer
#ENTRYPOINT /bin/bash
ENTRYPOINT /binaries/goreman -f dev/Procfile start
